package com.snapbizz.snaptoolkit.gdb.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DISTRIBUTOR_BRANCHES".
 */
public class DistributorBranches {

    private long phone;
    private long parentPhone;
    private String alternatePhones;
    /** Not-null value. */
    private String address;
    /** Not-null value. */
    private String name;
    private long tin;
    /** Not-null value. */
    private String city;
    /** Not-null value. */
    private String deliveryPincodes;
    private String email;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public DistributorBranches() {
    }

    public DistributorBranches(long phone) {
        this.phone = phone;
    }

    public DistributorBranches(long phone, long parentPhone, String alternatePhones, String address, String name, long tin, String city, String deliveryPincodes, String email, java.util.Date createdAt, java.util.Date updatedAt) {
        this.phone = phone;
        this.parentPhone = parentPhone;
        this.alternatePhones = alternatePhones;
        this.address = address;
        this.name = name;
        this.tin = tin;
        this.city = city;
        this.deliveryPincodes = deliveryPincodes;
        this.email = email;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public long getPhone() {
        return phone;
    }

    public void setPhone(long phone) {
        this.phone = phone;
    }

    public long getParentPhone() {
        return parentPhone;
    }

    public void setParentPhone(long parentPhone) {
        this.parentPhone = parentPhone;
    }

    public String getAlternatePhones() {
        return alternatePhones;
    }

    public void setAlternatePhones(String alternatePhones) {
        this.alternatePhones = alternatePhones;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public long getTin() {
        return tin;
    }

    public void setTin(long tin) {
        this.tin = tin;
    }

    /** Not-null value. */
    public String getCity() {
        return city;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCity(String city) {
        this.city = city;
    }

    /** Not-null value. */
    public String getDeliveryPincodes() {
        return deliveryPincodes;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeliveryPincodes(String deliveryPincodes) {
        this.deliveryPincodes = deliveryPincodes;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
