package com.snapbizz.snaptoolkit.gdb.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.snapbizz.snaptoolkit.gdb.dao.Distributors;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISTRIBUTORS".
*/
public class DistributorsDao extends AbstractDao<Distributors, Long> {

    public static final String TABLENAME = "DISTRIBUTORS";

    /**
     * Properties of entity Distributors.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Phone = new Property(0, long.class, "phone", true, "PHONE");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Address = new Property(2, String.class, "address", false, "ADDRESS");
        public final static Property City = new Property(3, String.class, "city", false, "CITY");
        public final static Property Email = new Property(4, String.class, "email", false, "EMAIL");
        public final static Property CreatedAt = new Property(5, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(6, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    };


    public DistributorsDao(DaoConfig config) {
        super(config);
    }
    
    public DistributorsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISTRIBUTORS\" (" + //
                "\"PHONE\" INTEGER PRIMARY KEY NOT NULL ," + // 0: phone
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"ADDRESS\" TEXT NOT NULL ," + // 2: address
                "\"CITY\" TEXT NOT NULL ," + // 3: city
                "\"EMAIL\" TEXT," + // 4: email
                "\"CREATED_AT\" INTEGER NOT NULL ," + // 5: createdAt
                "\"UPDATED_AT\" INTEGER NOT NULL );"); // 6: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISTRIBUTORS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Distributors entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPhone());
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getAddress());
        stmt.bindString(4, entity.getCity());
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(5, email);
        }
        stmt.bindLong(6, entity.getCreatedAt().getTime());
        stmt.bindLong(7, entity.getUpdatedAt().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Distributors readEntity(Cursor cursor, int offset) {
        Distributors entity = new Distributors( //
            cursor.getLong(offset + 0), // phone
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // address
            cursor.getString(offset + 3), // city
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // email
            new java.util.Date(cursor.getLong(offset + 5)), // createdAt
            new java.util.Date(cursor.getLong(offset + 6)) // updatedAt
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Distributors entity, int offset) {
        entity.setPhone(cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setAddress(cursor.getString(offset + 2));
        entity.setCity(cursor.getString(offset + 3));
        entity.setEmail(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreatedAt(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setUpdatedAt(new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Distributors entity, long rowId) {
        entity.setPhone(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Distributors entity) {
        if(entity != null) {
            return entity.getPhone();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
