package com.snapbizz.snaptoolkit.gdb.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DISTRIBUTOR_PRODUCTS".
 */
public class DistributorProducts {

    private long phone;
    private long productGid;

    public DistributorProducts() {
    }

    public DistributorProducts(long phone, long productGid) {
        this.phone = phone;
        this.productGid = productGid;
    }

    public long getPhone() {
        return phone;
    }

    public void setPhone(long phone) {
        this.phone = phone;
    }

    public long getProductGid() {
        return productGid;
    }

    public void setProductGid(long productGid) {
        this.productGid = productGid;
    }

}
