package com.snapbizz.snaptoolkit.gdb.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRODUCT_CATEGORIES".
 */
public class ProductCategories {

    private long id;
    /** Not-null value. */
    private String name;
    private Integer parentId;
    private int vatId;
    private boolean isQuickAdd;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public ProductCategories() {
    }

    public ProductCategories(long id) {
        this.id = id;
    }

    public ProductCategories(long id, String name, Integer parentId, int vatId, boolean isQuickAdd, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.name = name;
        this.parentId = parentId;
        this.vatId = vatId;
        this.isQuickAdd = isQuickAdd;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public int getVatId() {
        return vatId;
    }

    public void setVatId(int vatId) {
        this.vatId = vatId;
    }

    public boolean getIsQuickAdd() {
        return isQuickAdd;
    }

    public void setIsQuickAdd(boolean isQuickAdd) {
        this.isQuickAdd = isQuickAdd;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
