package com.snapbizz.snaptoolkit.gdb.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRODUCTS".
 */
public class Products {

    private long barcode;
    private long productGid;
    /** Not-null value. */
    private String name;
    private int mrp;
    private String alternateMrp;
    /** Not-null value. */
    private String uom;
    private int measure;
    private int brandId;
    private int categoryId;
    private Integer vatId;
    private boolean isDisabled;
    private String image;
    private String localName;
    private boolean isPc;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public Products() {
    }

    public Products(long barcode) {
        this.barcode = barcode;
    }

    public Products(long barcode, long productGid, String name, int mrp, String alternateMrp, String uom, int measure, int brandId, int categoryId, Integer vatId, boolean isDisabled, String image, String localName, boolean isPc, java.util.Date createdAt, java.util.Date updatedAt) {
        this.barcode = barcode;
        this.productGid = productGid;
        this.name = name;
        this.mrp = mrp;
        this.alternateMrp = alternateMrp;
        this.uom = uom;
        this.measure = measure;
        this.brandId = brandId;
        this.categoryId = categoryId;
        this.vatId = vatId;
        this.isDisabled = isDisabled;
        this.image = image;
        this.localName = localName;
        this.isPc = isPc;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public long getBarcode() {
        return barcode;
    }

    public void setBarcode(long barcode) {
        this.barcode = barcode;
    }

    public long getProductGid() {
        return productGid;
    }

    public void setProductGid(long productGid) {
        this.productGid = productGid;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getMrp() {
        return mrp;
    }

    public void setMrp(int mrp) {
        this.mrp = mrp;
    }

    public String getAlternateMrp() {
        return alternateMrp;
    }

    public void setAlternateMrp(String alternateMrp) {
        this.alternateMrp = alternateMrp;
    }

    /** Not-null value. */
    public String getUom() {
        return uom;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUom(String uom) {
        this.uom = uom;
    }

    public int getMeasure() {
        return measure;
    }

    public void setMeasure(int measure) {
        this.measure = measure;
    }

    public int getBrandId() {
        return brandId;
    }

    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }

    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public Integer getVatId() {
        return vatId;
    }

    public void setVatId(Integer vatId) {
        this.vatId = vatId;
    }

    public boolean getIsDisabled() {
        return isDisabled;
    }

    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getLocalName() {
        return localName;
    }

    public void setLocalName(String localName) {
        this.localName = localName;
    }

    public boolean getIsPc() {
        return isPc;
    }

    public void setIsPc(boolean isPc) {
        this.isPc = isPc;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
