package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CUSTOMER_DETAILS".
 */
public class CustomerDetails {

    private long phone;
    private int amountDue;
    private int purchaseValue;
    private int amountSaved;
    private Integer lastPurchaseAmount;
    private Integer lastPaymentAmount;
    private Integer avgPurchasePerVisit;
    private Float avgVisitsPerMonth;
    private java.util.Date lastPurchaseDate;
    private java.util.Date lastPaymentDate;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public CustomerDetails() {
    }

    public CustomerDetails(long phone) {
        this.phone = phone;
    }

    public CustomerDetails(long phone, int amountDue, int purchaseValue, int amountSaved, Integer lastPurchaseAmount, Integer lastPaymentAmount, Integer avgPurchasePerVisit, Float avgVisitsPerMonth, java.util.Date lastPurchaseDate, java.util.Date lastPaymentDate, java.util.Date createdAt, java.util.Date updatedAt) {
        this.phone = phone;
        this.amountDue = amountDue;
        this.purchaseValue = purchaseValue;
        this.amountSaved = amountSaved;
        this.lastPurchaseAmount = lastPurchaseAmount;
        this.lastPaymentAmount = lastPaymentAmount;
        this.avgPurchasePerVisit = avgPurchasePerVisit;
        this.avgVisitsPerMonth = avgVisitsPerMonth;
        this.lastPurchaseDate = lastPurchaseDate;
        this.lastPaymentDate = lastPaymentDate;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public long getPhone() {
        return phone;
    }

    public void setPhone(long phone) {
        this.phone = phone;
    }

    public int getAmountDue() {
        return amountDue;
    }

    public void setAmountDue(int amountDue) {
        this.amountDue = amountDue;
    }

    public int getPurchaseValue() {
        return purchaseValue;
    }

    public void setPurchaseValue(int purchaseValue) {
        this.purchaseValue = purchaseValue;
    }

    public int getAmountSaved() {
        return amountSaved;
    }

    public void setAmountSaved(int amountSaved) {
        this.amountSaved = amountSaved;
    }

    public Integer getLastPurchaseAmount() {
        return lastPurchaseAmount;
    }

    public void setLastPurchaseAmount(Integer lastPurchaseAmount) {
        this.lastPurchaseAmount = lastPurchaseAmount;
    }

    public Integer getLastPaymentAmount() {
        return lastPaymentAmount;
    }

    public void setLastPaymentAmount(Integer lastPaymentAmount) {
        this.lastPaymentAmount = lastPaymentAmount;
    }

    public Integer getAvgPurchasePerVisit() {
        return avgPurchasePerVisit;
    }

    public void setAvgPurchasePerVisit(Integer avgPurchasePerVisit) {
        this.avgPurchasePerVisit = avgPurchasePerVisit;
    }

    public Float getAvgVisitsPerMonth() {
        return avgVisitsPerMonth;
    }

    public void setAvgVisitsPerMonth(Float avgVisitsPerMonth) {
        this.avgVisitsPerMonth = avgVisitsPerMonth;
    }

    public java.util.Date getLastPurchaseDate() {
        return lastPurchaseDate;
    }

    public void setLastPurchaseDate(java.util.Date lastPurchaseDate) {
        this.lastPurchaseDate = lastPurchaseDate;
    }

    public java.util.Date getLastPaymentDate() {
        return lastPaymentDate;
    }

    public void setLastPaymentDate(java.util.Date lastPaymentDate) {
        this.lastPaymentDate = lastPaymentDate;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
