package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DISTRIBUTOR_PAYMENTS".
 */
public class DistributorPayments {

    private Long id;
    private Long poNumber;
    private Integer amount;
    /** Not-null value. */
    private String mode;
    private String reference;
    private boolean isDisabled;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public DistributorPayments() {
    }

    public DistributorPayments(Long id) {
        this.id = id;
    }

    public DistributorPayments(Long id, Long poNumber, Integer amount, String mode, String reference, boolean isDisabled, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.poNumber = poNumber;
        this.amount = amount;
        this.mode = mode;
        this.reference = reference;
        this.isDisabled = isDisabled;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPoNumber() {
        return poNumber;
    }

    public void setPoNumber(Long poNumber) {
        this.poNumber = poNumber;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /** Not-null value. */
    public String getMode() {
        return mode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMode(String mode) {
        this.mode = mode;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public boolean getIsDisabled() {
        return isDisabled;
    }

    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
