package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DISTRIBUTOR_ORDER_STATUS.
 */
public class DistributorOrderStatus {

    private Long id;
    private Long distributorId;
    private String statusString;
    private String orderId;
    private String orderNo;
    private String deliveryDate;
    private String statusCode;
    private Double orderSubTotal;
    private Double amountToPay;

    public DistributorOrderStatus() {
    }

    public DistributorOrderStatus(Long id) {
        this.id = id;
    }

    public DistributorOrderStatus(Long id, Long distributorId, String statusString, String orderId, String orderNo, String deliveryDate, String statusCode, Double orderSubTotal, Double amountToPay) {
        this.id = id;
        this.distributorId = distributorId;
        this.statusString = statusString;
        this.orderId = orderId;
        this.orderNo = orderNo;
        this.deliveryDate = deliveryDate;
        this.statusCode = statusCode;
        this.orderSubTotal = orderSubTotal;
        this.amountToPay = amountToPay;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDistributorId() {
        return distributorId;
    }

    public void setDistributorId(Long distributorId) {
        this.distributorId = distributorId;
    }

    public String getStatusString() {
        return statusString;
    }

    public void setStatusString(String statusString) {
        this.statusString = statusString;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getDeliveryDate() {
        return deliveryDate;
    }

    public void setDeliveryDate(String deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public String getStatusCode() {
        return statusCode;
    }

    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    public Double getOrderSubTotal() {
        return orderSubTotal;
    }

    public void setOrderSubTotal(Double orderSubTotal) {
        this.orderSubTotal = orderSubTotal;
    }

    public Double getAmountToPay() {
        return amountToPay;
    }

    public void setAmountToPay(Double amountToPay) {
        this.amountToPay = amountToPay;
    }

}
