package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DISTRIBUTOR_ORDER_TYPES.
 */
public class DistributorOrderTypes {

    private Long id;
    private Long distributorId;
    private String orderType;

    public DistributorOrderTypes() {
    }

    public DistributorOrderTypes(Long id) {
        this.id = id;
    }

    public DistributorOrderTypes(Long id, Long distributorId, String orderType) {
        this.id = id;
        this.distributorId = distributorId;
        this.orderType = orderType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDistributorId() {
        return distributorId;
    }

    public void setDistributorId(Long distributorId) {
        this.distributorId = distributorId;
    }

    public String getOrderType() {
        return orderType;
    }

    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

}
