package com.snapbizz.snaptoolkit.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.snapbizz.snaptoolkit.db.dao.DistributorDetails;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISTRIBUTOR_DETAILS".
*/
public class DistributorDetailsDao extends AbstractDao<DistributorDetails, Long> {

    public static final String TABLENAME = "DISTRIBUTOR_DETAILS";

    /**
     * Properties of entity DistributorDetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Phone = new Property(0, long.class, "phone", true, "PHONE");
        public final static Property AmountDue = new Property(1, int.class, "amountDue", false, "AMOUNT_DUE");
        public final static Property AmountPaid = new Property(2, int.class, "amountPaid", false, "AMOUNT_PAID");
        public final static Property LastPurchaseDate = new Property(3, java.util.Date.class, "lastPurchaseDate", false, "LAST_PURCHASE_DATE");
        public final static Property LastPaymentDate = new Property(4, java.util.Date.class, "lastPaymentDate", false, "LAST_PAYMENT_DATE");
        public final static Property LastPurchaseAmount = new Property(5, Integer.class, "lastPurchaseAmount", false, "LAST_PURCHASE_AMOUNT");
        public final static Property LastPaymentAmount = new Property(6, Integer.class, "lastPaymentAmount", false, "LAST_PAYMENT_AMOUNT");
        public final static Property CreatedAt = new Property(7, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(8, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    };


    public DistributorDetailsDao(DaoConfig config) {
        super(config);
    }
    
    public DistributorDetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISTRIBUTOR_DETAILS\" (" + //
                "\"PHONE\" INTEGER PRIMARY KEY NOT NULL ," + // 0: phone
                "\"AMOUNT_DUE\" INTEGER NOT NULL ," + // 1: amountDue
                "\"AMOUNT_PAID\" INTEGER NOT NULL ," + // 2: amountPaid
                "\"LAST_PURCHASE_DATE\" INTEGER," + // 3: lastPurchaseDate
                "\"LAST_PAYMENT_DATE\" INTEGER," + // 4: lastPaymentDate
                "\"LAST_PURCHASE_AMOUNT\" INTEGER," + // 5: lastPurchaseAmount
                "\"LAST_PAYMENT_AMOUNT\" INTEGER," + // 6: lastPaymentAmount
                "\"CREATED_AT\" INTEGER NOT NULL ," + // 7: createdAt
                "\"UPDATED_AT\" INTEGER NOT NULL );"); // 8: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISTRIBUTOR_DETAILS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DistributorDetails entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPhone());
        stmt.bindLong(2, entity.getAmountDue());
        stmt.bindLong(3, entity.getAmountPaid());
 
        java.util.Date lastPurchaseDate = entity.getLastPurchaseDate();
        if (lastPurchaseDate != null) {
            stmt.bindLong(4, lastPurchaseDate.getTime());
        }
 
        java.util.Date lastPaymentDate = entity.getLastPaymentDate();
        if (lastPaymentDate != null) {
            stmt.bindLong(5, lastPaymentDate.getTime());
        }
 
        Integer lastPurchaseAmount = entity.getLastPurchaseAmount();
        if (lastPurchaseAmount != null) {
            stmt.bindLong(6, lastPurchaseAmount);
        }
 
        Integer lastPaymentAmount = entity.getLastPaymentAmount();
        if (lastPaymentAmount != null) {
            stmt.bindLong(7, lastPaymentAmount);
        }
        stmt.bindLong(8, entity.getCreatedAt().getTime());
        stmt.bindLong(9, entity.getUpdatedAt().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DistributorDetails readEntity(Cursor cursor, int offset) {
        DistributorDetails entity = new DistributorDetails( //
            cursor.getLong(offset + 0), // phone
            cursor.getInt(offset + 1), // amountDue
            cursor.getInt(offset + 2), // amountPaid
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // lastPurchaseDate
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // lastPaymentDate
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // lastPurchaseAmount
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // lastPaymentAmount
            new java.util.Date(cursor.getLong(offset + 7)), // createdAt
            new java.util.Date(cursor.getLong(offset + 8)) // updatedAt
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DistributorDetails entity, int offset) {
        entity.setPhone(cursor.getLong(offset + 0));
        entity.setAmountDue(cursor.getInt(offset + 1));
        entity.setAmountPaid(cursor.getInt(offset + 2));
        entity.setLastPurchaseDate(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setLastPaymentDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setLastPurchaseAmount(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setLastPaymentAmount(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setCreatedAt(new java.util.Date(cursor.getLong(offset + 7)));
        entity.setUpdatedAt(new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DistributorDetails entity, long rowId) {
        entity.setPhone(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DistributorDetails entity) {
        if(entity != null) {
            return entity.getPhone();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
