package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DISTRIBUTOR_ORDERS.
 */
public class DistributorOrders {

    private Long id;
    private Long distributorId;
    private Short orderType;
    private Short orderStatus;
    private Long distributorStatus;

    public DistributorOrders() {
    }

    public DistributorOrders(Long id) {
        this.id = id;
    }

    public DistributorOrders(Long id, Long distributorId, Short orderType, Short orderStatus, Long distributorStatus) {
        this.id = id;
        this.distributorId = distributorId;
        this.orderType = orderType;
        this.orderStatus = orderStatus;
        this.distributorStatus = distributorStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDistributorId() {
        return distributorId;
    }

    public void setDistributorId(Long distributorId) {
        this.distributorId = distributorId;
    }

    public Short getOrderType() {
        return orderType;
    }

    public void setOrderType(Short orderType) {
        this.orderType = orderType;
    }

    public Short getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Long getDistributorStatus() {
        return distributorStatus;
    }

    public void setDistributorStatus(Long distributorStatus) {
        this.distributorStatus = distributorStatus;
    }

}
