package com.snapbizz.snaptoolkit.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.snapbizz.snaptoolkit.db.dao.DistributorOrderTypes;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DISTRIBUTOR_ORDER_TYPES.
*/
public class DistributorOrderTypesDao extends AbstractDao<DistributorOrderTypes, Long> {

    public static final String TABLENAME = "DISTRIBUTOR_ORDER_TYPES";

    /**
     * Properties of entity DistributorOrderTypes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DistributorId = new Property(1, Long.class, "distributorId", false, "DISTRIBUTOR_ID");
        public final static Property OrderType = new Property(2, String.class, "orderType", false, "ORDER_TYPE");
    };


    public DistributorOrderTypesDao(DaoConfig config) {
        super(config);
    }
    
    public DistributorOrderTypesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DISTRIBUTOR_ORDER_TYPES' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'DISTRIBUTOR_ID' INTEGER," + // 1: distributorId
                "'ORDER_TYPE' TEXT);"); // 2: orderType
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DISTRIBUTOR_ORDER_TYPES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DistributorOrderTypes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long distributorId = entity.getDistributorId();
        if (distributorId != null) {
            stmt.bindLong(2, distributorId);
        }
 
        String orderType = entity.getOrderType();
        if (orderType != null) {
            stmt.bindString(3, orderType);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DistributorOrderTypes readEntity(Cursor cursor, int offset) {
        DistributorOrderTypes entity = new DistributorOrderTypes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // distributorId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // orderType
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DistributorOrderTypes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDistributorId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setOrderType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DistributorOrderTypes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DistributorOrderTypes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
