package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DISTRIBUTOR_ORDER_ITEMS.
 */
public class DistributorOrderItems {

    private Long id;
    private Long distributorOrderId;
    private Long sku;
    private Integer orderedQ;
    private Integer acceptedQ;
    private Double mrp;
    private Double price;

    public DistributorOrderItems() {
    }

    public DistributorOrderItems(Long id) {
        this.id = id;
    }

    public DistributorOrderItems(Long id, Long distributorOrderId, Long sku, Integer orderedQ, Integer acceptedQ, Double mrp, Double price) {
        this.id = id;
        this.distributorOrderId = distributorOrderId;
        this.sku = sku;
        this.orderedQ = orderedQ;
        this.acceptedQ = acceptedQ;
        this.mrp = mrp;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDistributorOrderId() {
        return distributorOrderId;
    }

    public void setDistributorOrderId(Long distributorOrderId) {
        this.distributorOrderId = distributorOrderId;
    }

    public Long getSku() {
        return sku;
    }

    public void setSku(Long sku) {
        this.sku = sku;
    }

    public Integer getOrderedQ() {
        return orderedQ;
    }

    public void setOrderedQ(Integer orderedQ) {
        this.orderedQ = orderedQ;
    }

    public Integer getAcceptedQ() {
        return acceptedQ;
    }

    public void setAcceptedQ(Integer acceptedQ) {
        this.acceptedQ = acceptedQ;
    }

    public Double getMrp() {
        return mrp;
    }

    public void setMrp(Double mrp) {
        this.mrp = mrp;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

}
