package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INVENTORY".
 */
public class Inventory {

    private long productCode;
    private int quantity;
    private Integer minimumBaseQuantity;
    private Integer reOrderPoint;
    private boolean isDeleted;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public Inventory() {
    }

    public Inventory(long productCode) {
        this.productCode = productCode;
    }

    public Inventory(long productCode, int quantity, Integer minimumBaseQuantity, Integer reOrderPoint, boolean isDeleted, java.util.Date createdAt, java.util.Date updatedAt) {
        this.productCode = productCode;
        this.quantity = quantity;
        this.minimumBaseQuantity = minimumBaseQuantity;
        this.reOrderPoint = reOrderPoint;
        this.isDeleted = isDeleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public long getProductCode() {
        return productCode;
    }

    public void setProductCode(long productCode) {
        this.productCode = productCode;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public Integer getMinimumBaseQuantity() {
        return minimumBaseQuantity;
    }

    public void setMinimumBaseQuantity(Integer minimumBaseQuantity) {
        this.minimumBaseQuantity = minimumBaseQuantity;
    }

    public Integer getReOrderPoint() {
        return reOrderPoint;
    }

    public void setReOrderPoint(Integer reOrderPoint) {
        this.reOrderPoint = reOrderPoint;
    }

    public boolean getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
