package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INVOICES".
 */
public class Invoices {

    private Long id;
    private Long customerPhone;
    private boolean isMemo;
    private int totalAmount;
    private int pendingAmount;
    private int totalDiscount;
    private int totalSavings;
    private Long memoId;
    private boolean isCredit;
    private int totalQuantity;
    private int totalItems;
    private int totalVatAmount;
    private boolean isDeleted;
    private boolean isDelivery;
    private String billerName;
    /** Not-null value. */
    private String posName;
    private boolean isSync;
    private boolean isUpdated;
    /** Not-null value. */
    private java.util.Date billStartedAt;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public Invoices() {
    }

    public Invoices(Long id) {
        this.id = id;
    }

    public Invoices(Long id, Long customerPhone, boolean isMemo, int totalAmount, int pendingAmount, int totalDiscount, int totalSavings, Long memoId, boolean isCredit, int totalQuantity, int totalItems, int totalVatAmount, boolean isDeleted, boolean isDelivery, String billerName, String posName, boolean isSync, boolean isUpdated, java.util.Date billStartedAt, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.customerPhone = customerPhone;
        this.isMemo = isMemo;
        this.totalAmount = totalAmount;
        this.pendingAmount = pendingAmount;
        this.totalDiscount = totalDiscount;
        this.totalSavings = totalSavings;
        this.memoId = memoId;
        this.isCredit = isCredit;
        this.totalQuantity = totalQuantity;
        this.totalItems = totalItems;
        this.totalVatAmount = totalVatAmount;
        this.isDeleted = isDeleted;
        this.isDelivery = isDelivery;
        this.billerName = billerName;
        this.posName = posName;
        this.isSync = isSync;
        this.isUpdated = isUpdated;
        this.billStartedAt = billStartedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCustomerPhone() {
        return customerPhone;
    }

    public void setCustomerPhone(Long customerPhone) {
        this.customerPhone = customerPhone;
    }

    public boolean getIsMemo() {
        return isMemo;
    }

    public void setIsMemo(boolean isMemo) {
        this.isMemo = isMemo;
    }

    public int getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(int totalAmount) {
        this.totalAmount = totalAmount;
    }

    public int getPendingAmount() {
        return pendingAmount;
    }

    public void setPendingAmount(int pendingAmount) {
        this.pendingAmount = pendingAmount;
    }

    public int getTotalDiscount() {
        return totalDiscount;
    }

    public void setTotalDiscount(int totalDiscount) {
        this.totalDiscount = totalDiscount;
    }

    public int getTotalSavings() {
        return totalSavings;
    }

    public void setTotalSavings(int totalSavings) {
        this.totalSavings = totalSavings;
    }

    public Long getMemoId() {
        return memoId;
    }

    public void setMemoId(Long memoId) {
        this.memoId = memoId;
    }

    public boolean getIsCredit() {
        return isCredit;
    }

    public void setIsCredit(boolean isCredit) {
        this.isCredit = isCredit;
    }

    public int getTotalQuantity() {
        return totalQuantity;
    }

    public void setTotalQuantity(int totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    public int getTotalItems() {
        return totalItems;
    }

    public void setTotalItems(int totalItems) {
        this.totalItems = totalItems;
    }

    public int getTotalVatAmount() {
        return totalVatAmount;
    }

    public void setTotalVatAmount(int totalVatAmount) {
        this.totalVatAmount = totalVatAmount;
    }

    public boolean getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public boolean getIsDelivery() {
        return isDelivery;
    }

    public void setIsDelivery(boolean isDelivery) {
        this.isDelivery = isDelivery;
    }

    public String getBillerName() {
        return billerName;
    }

    public void setBillerName(String billerName) {
        this.billerName = billerName;
    }

    /** Not-null value. */
    public String getPosName() {
        return posName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPosName(String posName) {
        this.posName = posName;
    }

    public boolean getIsSync() {
        return isSync;
    }

    public void setIsSync(boolean isSync) {
        this.isSync = isSync;
    }

    public boolean getIsUpdated() {
        return isUpdated;
    }

    public void setIsUpdated(boolean isUpdated) {
        this.isUpdated = isUpdated;
    }

    /** Not-null value. */
    public java.util.Date getBillStartedAt() {
        return billStartedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBillStartedAt(java.util.Date billStartedAt) {
        this.billStartedAt = billStartedAt;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
