package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LAST_SYNC_TIME.
 */
public class LastSyncTime {

    private String syncClass;
    private java.util.Date timestamp;

    public LastSyncTime() {
    }

    public LastSyncTime(String syncClass) {
        this.syncClass = syncClass;
    }

    public LastSyncTime(String syncClass, java.util.Date timestamp) {
        this.syncClass = syncClass;
        this.timestamp = timestamp;
    }

    public String getSyncClass() {
        return syncClass;
    }

    public void setSyncClass(String syncClass) {
        this.syncClass = syncClass;
    }

    public java.util.Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(java.util.Date timestamp) {
        this.timestamp = timestamp;
    }

}
