package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORDER_DETAILS.
 */
public class OrderDetails {

    private Long id;
    private Integer poNumber;
    private Integer totalAmount;
    private Integer discount;
    private Integer vatAmount;
    private Float vatRate;
    private Integer mrp;
    private String name;
    private String uom;
    private Integer measure;
    private Integer orderedQuantity;
    private Integer acceptedQuantity;
    private Integer receivedQuantity;
    private Integer returnedQuantity;
    private Integer pickedupQuantity;
    private Long productCode;
    private Integer purchasePrice;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public OrderDetails() {
    }

    public OrderDetails(Long id) {
        this.id = id;
    }

    public OrderDetails(Long id, Integer poNumber, Integer totalAmount, Integer discount, Integer vatAmount, Float vatRate, Integer mrp, String name, String uom, Integer measure, Integer orderedQuantity, Integer acceptedQuantity, Integer receivedQuantity, Integer returnedQuantity, Integer pickedupQuantity, Long productCode, Integer purchasePrice, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.poNumber = poNumber;
        this.totalAmount = totalAmount;
        this.discount = discount;
        this.vatAmount = vatAmount;
        this.vatRate = vatRate;
        this.mrp = mrp;
        this.name = name;
        this.uom = uom;
        this.measure = measure;
        this.orderedQuantity = orderedQuantity;
        this.acceptedQuantity = acceptedQuantity;
        this.receivedQuantity = receivedQuantity;
        this.returnedQuantity = returnedQuantity;
        this.pickedupQuantity = pickedupQuantity;
        this.productCode = productCode;
        this.purchasePrice = purchasePrice;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPoNumber() {
        return poNumber;
    }

    public void setPoNumber(Integer poNumber) {
        this.poNumber = poNumber;
    }

    public Integer getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }

    public Integer getDiscount() {
        return discount;
    }

    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    public Integer getVatAmount() {
        return vatAmount;
    }

    public void setVatAmount(Integer vatAmount) {
        this.vatAmount = vatAmount;
    }

    public Float getVatRate() {
        return vatRate;
    }

    public void setVatRate(Float vatRate) {
        this.vatRate = vatRate;
    }

    public Integer getMrp() {
        return mrp;
    }

    public void setMrp(Integer mrp) {
        this.mrp = mrp;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUom() {
        return uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    public Integer getMeasure() {
        return measure;
    }

    public void setMeasure(Integer measure) {
        this.measure = measure;
    }

    public Integer getOrderedQuantity() {
        return orderedQuantity;
    }

    public void setOrderedQuantity(Integer orderedQuantity) {
        this.orderedQuantity = orderedQuantity;
    }

    public Integer getAcceptedQuantity() {
        return acceptedQuantity;
    }

    public void setAcceptedQuantity(Integer acceptedQuantity) {
        this.acceptedQuantity = acceptedQuantity;
    }

    public Integer getReceivedQuantity() {
        return receivedQuantity;
    }

    public void setReceivedQuantity(Integer receivedQuantity) {
        this.receivedQuantity = receivedQuantity;
    }

    public Integer getReturnedQuantity() {
        return returnedQuantity;
    }

    public void setReturnedQuantity(Integer returnedQuantity) {
        this.returnedQuantity = returnedQuantity;
    }

    public Integer getPickedupQuantity() {
        return pickedupQuantity;
    }

    public void setPickedupQuantity(Integer pickedupQuantity) {
        this.pickedupQuantity = pickedupQuantity;
    }

    public Long getProductCode() {
        return productCode;
    }

    public void setProductCode(Long productCode) {
        this.productCode = productCode;
    }

    public Integer getPurchasePrice() {
        return purchasePrice;
    }

    public void setPurchasePrice(Integer purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
