package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRODUCT_PACKS".
 */
public class ProductPacks {

    private long productCode;
    private Integer packSize;
    private Integer salePrice1;
    private Integer salePrice2;
    private Integer salePrice3;
    private boolean isDefault;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public ProductPacks() {
    }

    public ProductPacks(long productCode, Integer packSize, Integer salePrice1, Integer salePrice2, Integer salePrice3, boolean isDefault, java.util.Date createdAt, java.util.Date updatedAt) {
        this.productCode = productCode;
        this.packSize = packSize;
        this.salePrice1 = salePrice1;
        this.salePrice2 = salePrice2;
        this.salePrice3 = salePrice3;
        this.isDefault = isDefault;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public long getProductCode() {
        return productCode;
    }

    public void setProductCode(long productCode) {
        this.productCode = productCode;
    }

    public Integer getPackSize() {
        return packSize;
    }

    public void setPackSize(Integer packSize) {
        this.packSize = packSize;
    }

    public Integer getSalePrice1() {
        return salePrice1;
    }

    public void setSalePrice1(Integer salePrice1) {
        this.salePrice1 = salePrice1;
    }

    public Integer getSalePrice2() {
        return salePrice2;
    }

    public void setSalePrice2(Integer salePrice2) {
        this.salePrice2 = salePrice2;
    }

    public Integer getSalePrice3() {
        return salePrice3;
    }

    public void setSalePrice3(Integer salePrice3) {
        this.salePrice3 = salePrice3;
    }

    public boolean getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(boolean isDefault) {
        this.isDefault = isDefault;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
