package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PURCHASE_ORDERS".
 */
public class PurchaseOrders {

    private Long id;
    private long distributorPhone;
    private int totalAmount;
    private String distributorInvoiceNo;
    private int totalDiscount;
    private int pendingAmount;
    private int totalQuantity;
    private int totalItems;
    private int totalVat;
    private boolean isDeleted;
    private boolean isMemo;
    /** Not-null value. */
    private String status;
    /** Not-null value. */
    private java.util.Date orderDate;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public PurchaseOrders() {
    }

    public PurchaseOrders(Long id) {
        this.id = id;
    }

    public PurchaseOrders(Long id, long distributorPhone, int totalAmount, String distributorInvoiceNo, int totalDiscount, int pendingAmount, int totalQuantity, int totalItems, int totalVat, boolean isDeleted, boolean isMemo, String status, java.util.Date orderDate, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.distributorPhone = distributorPhone;
        this.totalAmount = totalAmount;
        this.distributorInvoiceNo = distributorInvoiceNo;
        this.totalDiscount = totalDiscount;
        this.pendingAmount = pendingAmount;
        this.totalQuantity = totalQuantity;
        this.totalItems = totalItems;
        this.totalVat = totalVat;
        this.isDeleted = isDeleted;
        this.isMemo = isMemo;
        this.status = status;
        this.orderDate = orderDate;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDistributorPhone() {
        return distributorPhone;
    }

    public void setDistributorPhone(long distributorPhone) {
        this.distributorPhone = distributorPhone;
    }

    public int getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(int totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getDistributorInvoiceNo() {
        return distributorInvoiceNo;
    }

    public void setDistributorInvoiceNo(String distributorInvoiceNo) {
        this.distributorInvoiceNo = distributorInvoiceNo;
    }

    public int getTotalDiscount() {
        return totalDiscount;
    }

    public void setTotalDiscount(int totalDiscount) {
        this.totalDiscount = totalDiscount;
    }

    public int getPendingAmount() {
        return pendingAmount;
    }

    public void setPendingAmount(int pendingAmount) {
        this.pendingAmount = pendingAmount;
    }

    public int getTotalQuantity() {
        return totalQuantity;
    }

    public void setTotalQuantity(int totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    public int getTotalItems() {
        return totalItems;
    }

    public void setTotalItems(int totalItems) {
        this.totalItems = totalItems;
    }

    public int getTotalVat() {
        return totalVat;
    }

    public void setTotalVat(int totalVat) {
        this.totalVat = totalVat;
    }

    public boolean getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public boolean getIsMemo() {
        return isMemo;
    }

    public void setIsMemo(boolean isMemo) {
        this.isMemo = isMemo;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** Not-null value. */
    public java.util.Date getOrderDate() {
        return orderDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderDate(java.util.Date orderDate) {
        this.orderDate = orderDate;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
