package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PURCHASE_ORDER_DETAILS".
 */
public class PurchaseOrderDetails {

    private Long id;
    private int poNumber;
    private int totalAmount;
    private int discount;
    private int vatAmount;
    private float vatRate;
    private int mrp;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String uom;
    private int measure;
    private int orderedQuantity;
    private int acceptedQuantity;
    private int receivedQuantity;
    private int returnedQuantity;
    private int pickedupQuantity;
    private long productCode;
    private int purchasePrice;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public PurchaseOrderDetails() {
    }

    public PurchaseOrderDetails(Long id) {
        this.id = id;
    }

    public PurchaseOrderDetails(Long id, int poNumber, int totalAmount, int discount, int vatAmount, float vatRate, int mrp, String name, String uom, int measure, int orderedQuantity, int acceptedQuantity, int receivedQuantity, int returnedQuantity, int pickedupQuantity, long productCode, int purchasePrice, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.poNumber = poNumber;
        this.totalAmount = totalAmount;
        this.discount = discount;
        this.vatAmount = vatAmount;
        this.vatRate = vatRate;
        this.mrp = mrp;
        this.name = name;
        this.uom = uom;
        this.measure = measure;
        this.orderedQuantity = orderedQuantity;
        this.acceptedQuantity = acceptedQuantity;
        this.receivedQuantity = receivedQuantity;
        this.returnedQuantity = returnedQuantity;
        this.pickedupQuantity = pickedupQuantity;
        this.productCode = productCode;
        this.purchasePrice = purchasePrice;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPoNumber() {
        return poNumber;
    }

    public void setPoNumber(int poNumber) {
        this.poNumber = poNumber;
    }

    public int getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(int totalAmount) {
        this.totalAmount = totalAmount;
    }

    public int getDiscount() {
        return discount;
    }

    public void setDiscount(int discount) {
        this.discount = discount;
    }

    public int getVatAmount() {
        return vatAmount;
    }

    public void setVatAmount(int vatAmount) {
        this.vatAmount = vatAmount;
    }

    public float getVatRate() {
        return vatRate;
    }

    public void setVatRate(float vatRate) {
        this.vatRate = vatRate;
    }

    public int getMrp() {
        return mrp;
    }

    public void setMrp(int mrp) {
        this.mrp = mrp;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getUom() {
        return uom;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUom(String uom) {
        this.uom = uom;
    }

    public int getMeasure() {
        return measure;
    }

    public void setMeasure(int measure) {
        this.measure = measure;
    }

    public int getOrderedQuantity() {
        return orderedQuantity;
    }

    public void setOrderedQuantity(int orderedQuantity) {
        this.orderedQuantity = orderedQuantity;
    }

    public int getAcceptedQuantity() {
        return acceptedQuantity;
    }

    public void setAcceptedQuantity(int acceptedQuantity) {
        this.acceptedQuantity = acceptedQuantity;
    }

    public int getReceivedQuantity() {
        return receivedQuantity;
    }

    public void setReceivedQuantity(int receivedQuantity) {
        this.receivedQuantity = receivedQuantity;
    }

    public int getReturnedQuantity() {
        return returnedQuantity;
    }

    public void setReturnedQuantity(int returnedQuantity) {
        this.returnedQuantity = returnedQuantity;
    }

    public int getPickedupQuantity() {
        return pickedupQuantity;
    }

    public void setPickedupQuantity(int pickedupQuantity) {
        this.pickedupQuantity = pickedupQuantity;
    }

    public long getProductCode() {
        return productCode;
    }

    public void setProductCode(long productCode) {
        this.productCode = productCode;
    }

    public int getPurchasePrice() {
        return purchasePrice;
    }

    public void setPurchasePrice(int purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
