package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRANSACTIONS".
 */
public class Transactions {

    private Long id;
    private Long invoiceId;
    /** Not-null value. */
    private String paymentType;
    /** Not-null value. */
    private String paymentMode;
    private String paymentReference;
    private int amount;
    private int remainingAmount;
    private Long customerPhone;
    private Long parentTransactionId;
    private boolean isSync;
    private boolean isUpdated;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public Transactions() {
    }

    public Transactions(Long id) {
        this.id = id;
    }

    public Transactions(Long id, Long invoiceId, String paymentType, String paymentMode, String paymentReference, int amount, int remainingAmount, Long customerPhone, Long parentTransactionId, boolean isSync, boolean isUpdated, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.invoiceId = invoiceId;
        this.paymentType = paymentType;
        this.paymentMode = paymentMode;
        this.paymentReference = paymentReference;
        this.amount = amount;
        this.remainingAmount = remainingAmount;
        this.customerPhone = customerPhone;
        this.parentTransactionId = parentTransactionId;
        this.isSync = isSync;
        this.isUpdated = isUpdated;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /** Not-null value. */
    public String getPaymentType() {
        return paymentType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    /** Not-null value. */
    public String getPaymentMode() {
        return paymentMode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    public String getPaymentReference() {
        return paymentReference;
    }

    public void setPaymentReference(String paymentReference) {
        this.paymentReference = paymentReference;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public int getRemainingAmount() {
        return remainingAmount;
    }

    public void setRemainingAmount(int remainingAmount) {
        this.remainingAmount = remainingAmount;
    }

    public Long getCustomerPhone() {
        return customerPhone;
    }

    public void setCustomerPhone(Long customerPhone) {
        this.customerPhone = customerPhone;
    }

    public Long getParentTransactionId() {
        return parentTransactionId;
    }

    public void setParentTransactionId(Long parentTransactionId) {
        this.parentTransactionId = parentTransactionId;
    }

    public boolean getIsSync() {
        return isSync;
    }

    public void setIsSync(boolean isSync) {
        this.isSync = isSync;
    }

    public boolean getIsUpdated() {
        return isUpdated;
    }

    public void setIsUpdated(boolean isUpdated) {
        this.isUpdated = isUpdated;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
