package com.snapbizz.snaptoolkit.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VAT.
 */
public class Vat {

    private Long id;
    private Float vatRate;
    private Integer stateId;
    private Integer categoryId;
    /** Not-null value. */
    private java.util.Date effectiveDate;
    /** Not-null value. */
    private java.util.Date updatedAt;

    public Vat() {
    }

    public Vat(Long id) {
        this.id = id;
    }

    public Vat(Long id, Float vatRate, Integer stateId, Integer categoryId, java.util.Date effectiveDate, java.util.Date updatedAt) {
        this.id = id;
        this.vatRate = vatRate;
        this.stateId = stateId;
        this.categoryId = categoryId;
        this.effectiveDate = effectiveDate;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getVatRate() {
        return vatRate;
    }

    public void setVatRate(Float vatRate) {
        this.vatRate = vatRate;
    }

    public Integer getStateId() {
        return stateId;
    }

    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /** Not-null value. */
    public java.util.Date getEffectiveDate() {
        return effectiveDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEffectiveDate(java.util.Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
