package com.snapbizz.snaptoolkit.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.snapbizz.snaptoolkit.db.dao.VatCategories;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VAT_CATEGORIES.
*/
public class VatCategoriesDao extends AbstractDao<VatCategories, Integer> {

    public static final String TABLENAME = "VAT_CATEGORIES";

    /**
     * Properties of entity VatCategories.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Integer.class, "id", true, "ID");
        public final static Property State = new Property(1, String.class, "state", false, "STATE");
        public final static Property VatRate = new Property(2, Float.class, "vatRate", false, "VAT_RATE");
        public final static Property CreatedAt = new Property(3, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(4, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    };


    public VatCategoriesDao(DaoConfig config) {
        super(config);
    }
    
    public VatCategoriesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VAT_CATEGORIES' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'STATE' TEXT," + // 1: state
                "'VAT_RATE' REAL," + // 2: vatRate
                "'CREATED_AT' INTEGER NOT NULL ," + // 3: createdAt
                "'UPDATED_AT' INTEGER NOT NULL );"); // 4: updatedAt
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_VAT_CATEGORIES_STATE ON VAT_CATEGORIES" +
                " (STATE);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VAT_CATEGORIES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, VatCategories entity) {
        stmt.clearBindings();
 
        Integer id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(2, state);
        }
 
        Float vatRate = entity.getVatRate();
        if (vatRate != null) {
            stmt.bindDouble(3, vatRate);
        }
        stmt.bindLong(4, entity.getCreatedAt().getTime());
        stmt.bindLong(5, entity.getUpdatedAt().getTime());
    }

    /** @inheritdoc */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public VatCategories readEntity(Cursor cursor, int offset) {
        VatCategories entity = new VatCategories( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // state
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // vatRate
            new java.util.Date(cursor.getLong(offset + 3)), // createdAt
            new java.util.Date(cursor.getLong(offset + 4)) // updatedAt
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, VatCategories entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setState(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVatRate(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setCreatedAt(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setUpdatedAt(new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Integer updateKeyAfterInsert(VatCategories entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public Integer getKey(VatCategories entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
