package com.snapbizz.snaptoolkit.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.snapbizz.snaptoolkit.db.dao.Vat;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VAT.
*/
public class VatDao extends AbstractDao<Vat, Long> {

    public static final String TABLENAME = "VAT";

    /**
     * Properties of entity Vat.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VatRate = new Property(1, Float.class, "vatRate", false, "VAT_RATE");
        public final static Property StateId = new Property(2, Integer.class, "stateId", false, "STATE_ID");
        public final static Property CategoryId = new Property(3, Integer.class, "categoryId", false, "CATEGORY_ID");
        public final static Property EffectiveDate = new Property(4, java.util.Date.class, "effectiveDate", false, "EFFECTIVE_DATE");
        public final static Property UpdatedAt = new Property(5, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    };


    public VatDao(DaoConfig config) {
        super(config);
    }
    
    public VatDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VAT' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'VAT_RATE' REAL," + // 1: vatRate
                "'STATE_ID' INTEGER," + // 2: stateId
                "'CATEGORY_ID' INTEGER," + // 3: categoryId
                "'EFFECTIVE_DATE' INTEGER NOT NULL ," + // 4: effectiveDate
                "'UPDATED_AT' INTEGER NOT NULL );"); // 5: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VAT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Vat entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Float vatRate = entity.getVatRate();
        if (vatRate != null) {
            stmt.bindDouble(2, vatRate);
        }
 
        Integer stateId = entity.getStateId();
        if (stateId != null) {
            stmt.bindLong(3, stateId);
        }
 
        Integer categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindLong(4, categoryId);
        }
        stmt.bindLong(5, entity.getEffectiveDate().getTime());
        stmt.bindLong(6, entity.getUpdatedAt().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Vat readEntity(Cursor cursor, int offset) {
        Vat entity = new Vat( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1), // vatRate
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // stateId
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // categoryId
            new java.util.Date(cursor.getLong(offset + 4)), // effectiveDate
            new java.util.Date(cursor.getLong(offset + 5)) // updatedAt
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Vat entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVatRate(cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1));
        entity.setStateId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCategoryId(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setEffectiveDate(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setUpdatedAt(new java.util.Date(cursor.getLong(offset + 5)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Vat entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Vat entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
