package com.snapbizz.snaptoolkit.utils;

public enum ChartType {
    REVENUE_DISTRIBUTOR,
    REVENUE_COMPANY,
    REVENUE_CATEGORY,
    STOCK_VALUE_DISTRIBUTOR,
    STOCK_VALUE_COMPANY,
    STOCK_VALUE_CATEGORY,
    DAYS_STOCK_DISTRIBUTOR,
    DAYS_STOCK_COMPANY,
    DAYS_STOCK_CATEGORY;
}
